export enum ActionsTypes {
  /* 
    Products Actions
  */
  GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS',
  FILTERED_PRODUCTS = 'FILTERED_PRODUCTS',


  /* 
    Order Actions
  */
  ADD_PRODUCTS_TO_ORDER = 'ADD_PRODUCTS_TO_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  INCREMENT_QUANTITY_OF_PRODUCT = 'INCREMENT_QUANTITY_OF_PRODUCT',
  DECREMENT_QUANTITY_OF_PRODUCT = 'DECREMENT_QUANTITY_OF_PRODUCT',

}
