export enum ActionsTypes {
  /* 
    Products Actions
  */
  GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS',
  FILTERED_PRODUCTS = 'FILTERED_PRODUCTS',


  /* 
    Order Actions
  */
  GET_OPEN_ORDER = 'GET_OPEN_ORDER',
  ADD_PRODUCTS_TO_ORDER = 'ADD_PRODUCTS_TO_ORDER',
  INCREMENT_QUANTITY_OF_PRODUCT = 'INCREMENT_QUANTITY_OF_PRODUCT',
  DECREMENT_QUANTITY_OF_PRODUCT = 'DECREMENT_QUANTITY_OF_PRODUCT',
  REMOVE_PRODUCTS_TO_ORDER = 'REMOVE_PRODUCTS_TO_ORDER',
  UPDATE_ADDRESS = 'UPDATE_ADDRESS',
  UPDATE_PAYMENT = 'UPDATE_PAYMENT',
  CONFIRM_ORDER = 'CONFIRM_ORDER',
}
